language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
    - /opt/graalvm-ce-1.0.0-rc16
env:
  - GRAALVM_HOME=/opt/graalvm-ce-1.0.0-rc16
before_script:
  - ./install-protobuf.sh
script:
  - mvn clean install -Pnative
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "jug-mz-quarkus"
  skip_cleanup: true
  file: ./target/backend-proxy-1.0-SNAPSHOT-runner
  on:
    branch: master
